### ISSUE TITLE
Gradle Build Fails

### ISSUE THREAD

**Issue by konsultaner** [ArangoDB-Community/aql-intellij-plugin#1]
It is probably an environment issue, but when I build the project I get the following error:

```
* What went wrong:
A problem occurred evaluating settings 'aql-intellij-plugin'.
> Could not find method jcenter() for arguments [] on object of type org.gradle.plugin.repository.internal.DefaultPluginRepositoriesSpec.

```

Do you have any Idea how to fix this?

apparently you need to add ` maven { url 'https://jcenter.bintray.com' }` this to the repos, but it didn't work..

**Comment by machak** [comment]
hm..never seen that one. What version of gradle are you using? I am running it with Gradle 4.10.2
version. Check also:

https://stackoverflow.com/questions/27470443/could-not-find-method-jcenter-for-arguments-on-repository-container

**Comment by konsultaner** [comment]
`gradle -v` outputs this:

```
Gradle 4.0.1
------------------------------------------------------------

Build time:   2017-07-07 14:02:41 UTC
Revision:     38e5dc0f772daecca1d2681885d3d85414eb6826

Groovy:       2.4.11
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_121 (Oracle Corporation 25.121-b13)
OS:           Windows 10 10.0 amd64
```

Should I update gradle?

**Comment by machak** [comment]
I have slightly different versions (see below) so, while you could try, I have a feeling it will not help. 
(disclaimer: I mostly work with maven so my Gradle knowledge is  quite limited)
------------------------------------------------------------
Gradle 4.10.2
------------------------------------------------------------

Build time:   2018-09-19 18:10:15 UTC
Revision:     b4d8d5d170bb4ba516e88d7fe5647e2323d791dd

Kotlin DSL:   1.0-rc-6
Kotlin:       1.2.61
Groovy:       2.4.15
Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
JVM:          1.8.0_162 (Oracle Corporation 25.162-b12)
OS:           Linux 4.18.0-12-generic amd64

**Comment by machak** [comment]
could you do an update and try again?
I removed plugin repo block, I think it is not needed at all.

**Comment by konsultaner** [comment]
I tried to build it with gradle 5, which is the latest and I got this:

```

> Task :test

com.arangodb.intellij.aql.grammar.generated.AqlParserTest > testAqlQueries FAILED
    java.lang.RuntimeException at AqlParserTest.java:24
        Caused by: java.io.FileNotFoundException at AqlParserTest.java:24

com.arangodb.intellij.aql.syntax.AqlCommenterTest > testComment FAILED
    java.lang.RuntimeException at AqlCommenterTest.java:13
        Caused by: java.io.FileNotFoundException at AqlCommenterTest.java:13

com.arangodb.intellij.aql.syntax.AqlCommenterTest > testBlockComment FAILED
    java.lang.RuntimeException at AqlCommenterTest.java:19
        Caused by: java.io.FileNotFoundException at AqlCommenterTest.java:19
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=250m; support was removed in 8.0

6 tests completed, 3 failed

> Task :test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> There were failing tests. See the report at: file:///C:/Users/Richard%20Burkhardt/IdeaProjects/aql-intellij-plugin/build/reports/tests/test/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 21s
14 actionable tasks: 3 executed, 11 up-to-date
```

**Comment by konsultaner** [comment]
I'm on java 8_121

**Comment by machak** [comment]
@konsultaner  
that is bit unfortunate and a known issue I still need to fix (Intellij test fixtures related issue)
You can skip test for now by running it with:
gradle build -x test

**Comment by konsultaner** [comment]
@machak THANK YOU! It worked
