### ISSUE TITLE
Cant set database in intellij 2021.2.3

### ISSUE THREAD

**Issue by amitgilad3** [ArangoDB-Community/aql-intellij-plugin#24]
After installing the plugin and trying to run a aql query i get the following error: No database set for ArangoDB data source

and when i try to set the database i cant configure it 
![Screen Shot 2021-11-14 at 12 01 19](https://user-images.githubusercontent.com/7702311/141676577-585f11cf-d37e-442d-92d3-46c30ba052bc.png)

**Comment by amit-enso** [comment]
@machak the issue is still not resolved,  when i click on test server all is good  but i still cant choose a db , any thoughts ?

**Comment by andrewzielinski** [comment]
I'm also facing this issue.  Can you please fix as I would love to use the plugin. I'm using Intellij 2021.3.3

**Comment by meowalien** [comment]
I have the same problem too ...

**Comment by meowalien** [comment]
@andrewzielinski @amit-enso @amitgilad3 
I found that as long as I enter the root password, it can be used normally.
seems like it canot connect to db with no password root.

**Comment by cw00dw0rd** [comment]
To clarify the issue, is it that the plugin is requiring a root user or just that the root user (or any user) has a password?

It may warrant a feature request if it is the former.

**Comment by meowalien** [comment]
@cw00dw0rd 
Any user has a password.

**Comment by andrewzielinski** [comment]
@meowalien Unfortunately I don't have root access :(
