### ISSUE TITLE
Not available on IntelliJ IDEA 2019.x

### ISSUE THREAD

**Issue by dam5s** [ArangoDB-Community/aql-intellij-plugin#9]
This plugin is not available in the marketplace for the latest version of IntelliJ IDEA. According to the Jetbrains website it's only available for IntelliJ IDEA up to 2018.3.6

https://plugins.jetbrains.com/plugin/11397-aql-arangodb-query-language-/versions

**Comment by sh0umik** [comment]
Any updates on this ?

**Comment by machak** [comment]
pending review, uploaded 2019.2+ release

**Comment by machak** [comment]
new version should be available in plugin repo
